---
title: "covid_analysis"
author: "Martyna Stajniak"
date: "2025-01-14"
output:
  html_document: default
  pdf_document: default
  always_allow_html: yes
  word_document: default
---

COVID-19 Data Visualization 
```{r}
library( "ggpmisc")
library("ggplot2")
library("plotly")
library(readr)

# I am using total_cases.csv dataset. This dataset contains only two columns: date and cases.

total_cases <- read_csv("C:/Users/Martynaa/Desktop/portfolio/analizy_R/total_cases.csv")
head(total_cases)

# Structure:
str(total_cases)

# Summary:
summary(total_cases)

# Dimensions:
dim(total_cases)

# Interactive chart
first_chart <- ggplot(total_cases, aes(x = date, y = cases)) +
  geom_line(color = "blue") +
  labs(title = "Number of COVID-19 cases",
       x = "Date",
       y = "Sum: confirmed cases") 

# conversion:
ggplotly(first_chart)

# Histogram and density plot
ggplot(total_cases, aes(x=cases)) + geom_histogram(aes(y=..density..), color="black", fill="white") +
  geom_density(color="lightpink", fill="lightpink", alpha=0.4) +
  theme(plot.background = element_rect("white"), panel.background = element_rect("white"), axis.line = element_line("black"), panel.grid.major = element_line(colour = "grey50") ) +
  labs(title = "Histogram and density plot")


```

```{r}
# This dataset presents 7 countries and total cases each day 
top7<-read.csv("C:/Users/Martynaa/Desktop/portfolio/analizy_R/top7_02_2020.csv")
head(top7)

# Structure: 
str(top7)

# Summarise:
summarise(top7)

# Color-coded chart by country
ggplot(data = top7, aes(x = date, y = cum_cases, col = country)) +
  geom_point() +
  scale_y_log10() +
  labs(title = "Color-coded chart by country", x = "Date", y = "Cum_cases") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

# Infection trend over time 
ggplot(data = top7, aes(x = as.Date(date), y = cum_cases, color = country)) +
  geom_line() +
  labs(title = "Infection trend over time", x = "Date", y = "Cum_sum")

# Comparison of the number of cases on a logarithmic scale, now we can better capture growth proportions.
ggplot(data = top7, aes(x = as.Date(date), y = cum_cases, color = country)) +
  geom_line() +
  scale_y_log10() +
  labs(title = "Comparison of the number of cases on a logarithmic scale", x = "Date", y = "Cum_sum (log)")

# Number of cases on selected days:  start, middle, end
selected_dates <- top7 %>% filter(date %in% c("2020-02-18", "2020-03-01", "2020-03-15"))
ggplot(data = selected_dates, aes(x = country, y = cum_cases, fill = country)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~date) +
  labs(title = "Number of cases on selected days", x = "Country", y = "Number of Cases") + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

# Percentage of countries in the global number of cases
total_cases_by_country <- top7 %>%
  group_by(country) %>%
  summarise(total_cases = max(cum_cases, na.rm = TRUE))

total_cases_by_country <- total_cases_by_country %>%
  mutate(percentage = (total_cases / sum(total_cases)) * 100)

ggplot(data = total_cases_by_country, aes(x = reorder(country, -percentage), y = percentage, fill = country)) +
  geom_bar(stat = "identity") +
  labs(title = "Percentage of countries in the global number of cases", x = "Country", y = "Percentage")

#Heatmap 

ggplot(data = top7, aes(x = as.Date(date), y = country, fill = cum_cases)) +
  geom_tile() +
  labs(title = "Heatmap of cases over time", x = "Date", y = "Country") +
  scale_fill_gradient(low = "white", high = "red")

```

```{r}
library(dplyr)
# This dataset presents countries, theis provinces , date and cases 
data_c <- read_csv("C:/Users/Martynaa/Desktop/portfolio/analizy_R/cases_by_country.csv")
head(data_c)

# Structure 
str(data_c)

# Summary
summary(data_c)

# top 9
top<-data_c %>%  group_by(country) %>% summarise(country=n(), max=max(cum_cases))
top
top9<- top %>% arrange(desc(max)) %>% slice_head(n=9) %>% select(country, max)
top9

# As we can see top 7 caoutries with a highiest rate of covid cases is in the same countries as in a previous dataset

#Interactive chart for USA provinces 
dane <-data_c %>% filter(date > as.Date("2020-02-20") & country=="US")
dane
plot_ly(data=dane, x=~date, y=~cases , color = ~province, colors = RColorBrewer::brewer.pal(8, "Set2"), type="scatter", mode="markers")

```